export const migration001 = `
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, google_sub TEXT NOT NULL UNIQUE, email TEXT NOT NULL, email_verified INTEGER NOT NULL, name TEXT NOT NULL, avatar_url TEXT, provider TEXT NOT NULL CHECK(provider='GOOGLE'), role TEXT NOT NULL CHECK(role IN ('USER','ADMIN')) DEFAULT 'USER', status TEXT NOT NULL CHECK(status IN ('ACTIVE','SUSPENDED','DISABLED','DELETED')) DEFAULT 'ACTIVE', permissions TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, last_login_at TEXT, last_activity_at TEXT, deleted_at TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS users_provider_google_sub_idx ON users(provider, google_sub);
CREATE TABLE IF NOT EXISTS devices (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, fingerprint_hash TEXT NOT NULL, label TEXT, first_seen_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, ip_address TEXT, user_agent TEXT, UNIQUE(user_id, fingerprint_hash));
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, device_id TEXT NOT NULL REFERENCES devices(id), created_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, expires_at TEXT NOT NULL, revoked_at TEXT, ip_address TEXT, user_agent TEXT);
CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions(user_id, revoked_at, expires_at);
CREATE TABLE IF NOT EXISTS login_history (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id) ON DELETE SET NULL, provider TEXT NOT NULL, success INTEGER NOT NULL, failure_reason TEXT, timestamp TEXT NOT NULL, ip_address TEXT, user_agent TEXT, metadata TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS security_events (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id) ON DELETE SET NULL, event_type TEXT NOT NULL, severity TEXT NOT NULL, metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL, action TEXT NOT NULL, resource_type TEXT NOT NULL, resource_id TEXT, metadata TEXT NOT NULL DEFAULT '{}', timestamp TEXT NOT NULL);`;
