import type { Db } from '../db/database.js'; import { now, uuid } from '../security/crypto.js'; import type { Session, User, UserStatus } from './types.js';
const mapUser=(r:any):User=>({id:r.id,googleSub:r.google_sub,email:r.email,emailVerified:!!r.email_verified,name:r.name,avatarUrl:r.avatar_url,provider:'GOOGLE',role:r.role,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at,lastLoginAt:r.last_login_at,lastActivityAt:r.last_activity_at,deletedAt:r.deleted_at,permissions:JSON.parse(r.permissions||'[]')});
const mapSession=(r:any):Session=>({id:r.id,userId:r.user_id,tokenHash:r.token_hash,deviceId:r.device_id,createdAt:r.created_at,lastSeenAt:r.last_seen_at,expiresAt:r.expires_at,revokedAt:r.revoked_at,ipAddress:r.ip_address,userAgent:r.user_agent});
export class AuthRepository { constructor(private db:Db){}
 findUserByGoogleSub(sub:string){ const r=this.db.prepare('SELECT * FROM users WHERE provider=? AND google_sub=?').get('GOOGLE',sub); return r?mapUser(r):null; }
 findUserById(id:string){ const r=this.db.prepare('SELECT * FROM users WHERE id=?').get(id); return r?mapUser(r):null; }
 upsertGoogleUser(c:{sub:string;email:string;emailVerified:boolean;name:string;avatarUrl?:string|null}){ const t=now(); const id=uuid(); this.db.prepare(`INSERT INTO users(id,google_sub,email,email_verified,name,avatar_url,provider,role,status,created_at,updated_at,last_login_at,last_activity_at,permissions) VALUES(?,?,?,?,?,?,'GOOGLE','USER','ACTIVE',?,?,?,?, '[]') ON CONFLICT(google_sub) DO UPDATE SET email=excluded.email,email_verified=excluded.email_verified,avatar_url=excluded.avatar_url,updated_at=excluded.updated_at,last_login_at=excluded.last_login_at,last_activity_at=excluded.last_activity_at`).run(id,c.sub,c.email,c.emailVerified?1:0,c.name,c.avatarUrl||null,t,t,t,t); return this.findUserByGoogleSub(c.sub)!; }
 updateUserStatus(id:string,status:UserStatus){ this.db.prepare('UPDATE users SET status=?, updated_at=? WHERE id=?').run(status,now(),id); }
 upsertDevice(userId:string,fingerprintHash:string,ip:string|null,ua:string|null){ const id=uuid(), t=now(); this.db.prepare(`INSERT INTO devices(id,user_id,fingerprint_hash,first_seen_at,last_seen_at,ip_address,user_agent) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,fingerprint_hash) DO UPDATE SET last_seen_at=excluded.last_seen_at, ip_address=excluded.ip_address, user_agent=excluded.user_agent`).run(id,userId,fingerprintHash,t,t,ip,ua); return this.db.prepare('SELECT id FROM devices WHERE user_id=? AND fingerprint_hash=?').get(userId,fingerprintHash) as {id:string}; }
 createSession(s:{userId:string;tokenHash:string;deviceId:string;expiresAt:string;ip:string|null;ua:string|null}){ const id=uuid(), t=now(); this.db.prepare('INSERT INTO sessions(id,user_id,token_hash,device_id,created_at,last_seen_at,expires_at,ip_address,user_agent) VALUES(?,?,?,?,?,?,?,?,?)').run(id,s.userId,s.tokenHash,s.deviceId,t,t,s.expiresAt,s.ip,s.ua); return this.findSessionByHash(s.tokenHash)!; }
 findSessionByHash(hash:string){ const r=this.db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(hash); return r?mapSession(r):null; }
 listSessions(userId:string){ return this.db.prepare('SELECT * FROM sessions WHERE user_id=? ORDER BY created_at DESC').all(userId).map(mapSession); }
 touchSession(id:string){ this.db.prepare('UPDATE sessions SET last_seen_at=? WHERE id=?').run(now(),id); }
 revokeSession(id:string,userId:string){ this.db.prepare('UPDATE sessions SET revoked_at=COALESCE(revoked_at,?) WHERE id=? AND user_id=?').run(now(),id,userId); }
 revokeAll(userId:string){ this.db.prepare('UPDATE sessions SET revoked_at=COALESCE(revoked_at,?) WHERE user_id=?').run(now(),userId); }
 recordLogin(userId:string|null,success:boolean,reason:string|null,ip:string|null,ua:string|null,metadata={}){ this.db.prepare('INSERT INTO login_history(id,user_id,provider,success,failure_reason,timestamp,ip_address,user_agent,metadata) VALUES(?,?,?,?,?,?,?,?,?)').run(uuid(),userId,'GOOGLE',success?1:0,reason,now(),ip,ua,JSON.stringify(metadata)); }
 security(userId:string|null,event_type:string,severity='info',metadata={}){ this.db.prepare('INSERT INTO security_events(id,user_id,event_type,severity,metadata,created_at) VALUES(?,?,?,?,?,?)').run(uuid(),userId,event_type,severity,JSON.stringify(metadata),now()); }
 audit(actor:string|null,action:string,resourceType:string,resourceId:string|null,metadata={}){ this.db.prepare('INSERT INTO audit_logs(id,actor_user_id,action,resource_type,resource_id,metadata,timestamp) VALUES(?,?,?,?,?,?,?)').run(uuid(),actor,action,resourceType,resourceId,JSON.stringify(metadata),now()); }
}
